### ISSUE TITLE
Make errors

### ISSUE THREAD

**Issue by gsingh1** [mlab-upenn/GrooveNet#1]
gsingh@gsingh-virtual-machine:~/Downloads$ cd GrooveNet-master
gsingh@gsingh-virtual-machine:~/Downloads/GrooveNet-master$ cd project
gsingh@gsingh-virtual-machine:~/Downloads/GrooveNet-master/project$ make clean
make: **\* No rule to make target `clean'. Stop.
gsingh@gsingh-virtual-machine:~/Downloads/GrooveNet-master/project$ make
make: **\* No targets specified and no makefile found. Stop.
gsingh@gsingh-virtual-machine:~/Downloads/GrooveNet-master/project$

I keep getting make errors, no make file in project folder. Any ideas?

**Comment by PennTao** [comment]
Can you send me the error messages?

**Comment by PennTao** [comment]
Yes, the x button will not work, the only way to exit is press ctrl+c. The
terminal should be kept open.

best,
Tao
